// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: iam.proto

package server

import (
	"context"

	"github.com/ziptako/iam/iam"
	"github.com/ziptako/iam/internal/logic/permissionservice"
	"github.com/ziptako/iam/internal/svc"
)

type PermissionServiceServer struct {
	svcCtx *svc.ServiceContext
	iam.UnimplementedPermissionServiceServer
}

func NewPermissionServiceServer(svcCtx *svc.ServiceContext) *PermissionServiceServer {
	return &PermissionServiceServer{
		svcCtx: svcCtx,
	}
}

// CreatePermission 创建新权限
func (s *PermissionServiceServer) CreatePermission(ctx context.Context, in *iam.CreatePermissionRequest) (*iam.CreatePermissionResponse, error) {
	l := permissionservicelogic.NewCreatePermissionLogic(ctx, s.svcCtx)
	return l.CreatePermission(in)
}

// GetPermission 根据ID获取权限详情
func (s *PermissionServiceServer) GetPermission(ctx context.Context, in *iam.GetPermissionRequest) (*iam.Permission, error) {
	l := permissionservicelogic.NewGetPermissionLogic(ctx, s.svcCtx)
	return l.GetPermission(in)
}

// UpdatePermission 更新权限信息
func (s *PermissionServiceServer) UpdatePermission(ctx context.Context, in *iam.UpdatePermissionRequest) (*iam.Permission, error) {
	l := permissionservicelogic.NewUpdatePermissionLogic(ctx, s.svcCtx)
	return l.UpdatePermission(in)
}

// DeletePermission 删除权限（软删除）
func (s *PermissionServiceServer) DeletePermission(ctx context.Context, in *iam.DeletePermissionRequest) (*iam.DeletePermissionResponse, error) {
	l := permissionservicelogic.NewDeletePermissionLogic(ctx, s.svcCtx)
	return l.DeletePermission(in)
}

// ListPermissions 分页查询权限列表
func (s *PermissionServiceServer) ListPermissions(ctx context.Context, in *iam.ListPermissionsRequest) (*iam.ListPermissionsResponse, error) {
	l := permissionservicelogic.NewListPermissionsLogic(ctx, s.svcCtx)
	return l.ListPermissions(in)
}
