// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: iam.proto

package permissionservice

import (
	"context"

	"github.com/ziptako/iam/iam"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AssignRolePermissionRequest   = iam.AssignRolePermissionRequest
	AssignRolePermissionResponse  = iam.AssignRolePermissionResponse
	AssignRolePermissionsRequest  = iam.AssignRolePermissionsRequest
	AssignRolePermissionsResponse = iam.AssignRolePermissionsResponse
	AssignUserRoleRequest         = iam.AssignUserRoleRequest
	AssignUserRoleResponse        = iam.AssignUserRoleResponse
	AssignUserRolesRequest        = iam.AssignUserRolesRequest
	AssignUserRolesResponse       = iam.AssignUserRolesResponse
	ChangePasswordRequest         = iam.ChangePasswordRequest
	ChangePasswordResponse        = iam.ChangePasswordResponse
	CheckRolePermissionRequest    = iam.CheckRolePermissionRequest
	CheckRolePermissionResponse   = iam.CheckRolePermissionResponse
	CheckUserPermissionRequest    = iam.CheckUserPermissionRequest
	CheckUserPermissionResponse   = iam.CheckUserPermissionResponse
	CheckUserRoleRequest          = iam.CheckUserRoleRequest
	CheckUserRoleResponse         = iam.CheckUserRoleResponse
	CreatePermissionRequest       = iam.CreatePermissionRequest
	CreatePermissionResponse      = iam.CreatePermissionResponse
	CreateRoleRequest             = iam.CreateRoleRequest
	CreateRoleResponse            = iam.CreateRoleResponse
	CreateUserRequest             = iam.CreateUserRequest
	CreateUserResponse            = iam.CreateUserResponse
	DeletePermissionRequest       = iam.DeletePermissionRequest
	DeletePermissionResponse      = iam.DeletePermissionResponse
	DeleteRoleRequest             = iam.DeleteRoleRequest
	DeleteRoleResponse            = iam.DeleteRoleResponse
	DeleteUserRequest             = iam.DeleteUserRequest
	DeleteUserResponse            = iam.DeleteUserResponse
	GetPermissionRequest          = iam.GetPermissionRequest
	GetRolePermissionsRequest     = iam.GetRolePermissionsRequest
	GetRolePermissionsResponse    = iam.GetRolePermissionsResponse
	GetRoleRequest                = iam.GetRoleRequest
	GetUserByUsernameRequest      = iam.GetUserByUsernameRequest
	GetUserRequest                = iam.GetUserRequest
	GetUserRolesRequest           = iam.GetUserRolesRequest
	GetUserRolesResponse          = iam.GetUserRolesResponse
	ListPermissionsRequest        = iam.ListPermissionsRequest
	ListPermissionsResponse       = iam.ListPermissionsResponse
	ListRolesRequest              = iam.ListRolesRequest
	ListRolesResponse             = iam.ListRolesResponse
	ListUsersRequest              = iam.ListUsersRequest
	ListUsersResponse             = iam.ListUsersResponse
	Permission                    = iam.Permission
	RemoveRolePermissionRequest   = iam.RemoveRolePermissionRequest
	RemoveRolePermissionResponse  = iam.RemoveRolePermissionResponse
	RemoveRolePermissionsRequest  = iam.RemoveRolePermissionsRequest
	RemoveRolePermissionsResponse = iam.RemoveRolePermissionsResponse
	RemoveUserRoleRequest         = iam.RemoveUserRoleRequest
	RemoveUserRoleResponse        = iam.RemoveUserRoleResponse
	RemoveUserRolesRequest        = iam.RemoveUserRolesRequest
	RemoveUserRolesResponse       = iam.RemoveUserRolesResponse
	Role                          = iam.Role
	UpdatePermissionRequest       = iam.UpdatePermissionRequest
	UpdateRoleRequest             = iam.UpdateRoleRequest
	UpdateUserRequest             = iam.UpdateUserRequest
	User                          = iam.User
	VerifyPasswordRequest         = iam.VerifyPasswordRequest
	VerifyPasswordResponse        = iam.VerifyPasswordResponse

	PermissionService interface {
		// CreatePermission 创建新权限
		CreatePermission(ctx context.Context, in *CreatePermissionRequest, opts ...grpc.CallOption) (*CreatePermissionResponse, error)
		// GetPermission 根据ID获取权限详情
		GetPermission(ctx context.Context, in *GetPermissionRequest, opts ...grpc.CallOption) (*Permission, error)
		// UpdatePermission 更新权限信息
		UpdatePermission(ctx context.Context, in *UpdatePermissionRequest, opts ...grpc.CallOption) (*Permission, error)
		// DeletePermission 删除权限（软删除）
		DeletePermission(ctx context.Context, in *DeletePermissionRequest, opts ...grpc.CallOption) (*DeletePermissionResponse, error)
		// ListPermissions 分页查询权限列表
		ListPermissions(ctx context.Context, in *ListPermissionsRequest, opts ...grpc.CallOption) (*ListPermissionsResponse, error)
	}

	defaultPermissionService struct {
		cli zrpc.Client
	}
)

func NewPermissionService(cli zrpc.Client) PermissionService {
	return &defaultPermissionService{
		cli: cli,
	}
}

// CreatePermission 创建新权限
func (m *defaultPermissionService) CreatePermission(ctx context.Context, in *CreatePermissionRequest, opts ...grpc.CallOption) (*CreatePermissionResponse, error) {
	client := iam.NewPermissionServiceClient(m.cli.Conn())
	return client.CreatePermission(ctx, in, opts...)
}

// GetPermission 根据ID获取权限详情
func (m *defaultPermissionService) GetPermission(ctx context.Context, in *GetPermissionRequest, opts ...grpc.CallOption) (*Permission, error) {
	client := iam.NewPermissionServiceClient(m.cli.Conn())
	return client.GetPermission(ctx, in, opts...)
}

// UpdatePermission 更新权限信息
func (m *defaultPermissionService) UpdatePermission(ctx context.Context, in *UpdatePermissionRequest, opts ...grpc.CallOption) (*Permission, error) {
	client := iam.NewPermissionServiceClient(m.cli.Conn())
	return client.UpdatePermission(ctx, in, opts...)
}

// DeletePermission 删除权限（软删除）
func (m *defaultPermissionService) DeletePermission(ctx context.Context, in *DeletePermissionRequest, opts ...grpc.CallOption) (*DeletePermissionResponse, error) {
	client := iam.NewPermissionServiceClient(m.cli.Conn())
	return client.DeletePermission(ctx, in, opts...)
}

// ListPermissions 分页查询权限列表
func (m *defaultPermissionService) ListPermissions(ctx context.Context, in *ListPermissionsRequest, opts ...grpc.CallOption) (*ListPermissionsResponse, error) {
	client := iam.NewPermissionServiceClient(m.cli.Conn())
	return client.ListPermissions(ctx, in, opts...)
}
